services:
  react-app:
    build: ./client
    image: react-app
    restart: unless-stopped
    ports:
     - "127.0.0.1:8080:80"
    networks:
      - premed
    depends_on:
      - api-server

  api-server:
    build: ./server
    image: api-server
    restart: unless-stopped
    ports:
      - "5001:5000"
    networks:
      - premed
    depends_on:
      - mongodb

    env_file:
      - .env

    environment:
      PORT: "5000"
      NODE_ENV: "production"
      MONGO_URI: "mongodb://${DB_USER}:${DB_PASS}@mongodb:27017/${DB_NAME}?authSource=admin"
      JWT_SECRET: "${JWT_SECRET}"
      JWT_SECRET_REFRESH: "${JWT_SECRET_REFRESH}"

    command: ["sh", "-c", "node build/src/index.js"]

  mongodb:
    image: mongo:4.4-bionic
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MONGO_INITDB_DATABASE: "${DB_NAME}"
      MONGO_INITDB_ROOT_USERNAME: "${DB_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${DB_PASS}"
    ports:
      - "27017:27017"
    networks:
      - premed
    volumes:
      - mongo:/data/db

networks:
  premed:
    driver: bridge

volumes:
  mongo:
    driver: local
